version: "3.7"
services:
  app:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2021-09-15T04-54-25Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - local-drive:/data
volumes:
  local-drive: